<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DshDesktopUpdater</AssemblyName>
    <RootNamespace>DshDesktopUpdater</RootNamespace>
    <ApplicationIcon>..\..\src\app.ico</ApplicationIcon>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Product>DeepSeek Harness 桌面版 更新助手</Product>
    <Company>贤余sama</Company>
    <Version>1.3.0</Version>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Updater.Core\Updater.Core.csproj" />
  </ItemGroup>

</Project>
